# Generated by Django 5.2.1 on 2025-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medicllm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
